version: 2.1

jobs:
  build:
    docker: 
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Show Current Directory
          command: ls  # or pwd
      - run:
          name: Install dependencies and build project
          command: |
            cd /nextJS/src
            npm install
            npm run
      - sonarcloud/scan

orbs:
  sonarcloud: sonarsource/sonarcloud@2.0.0

workflows:
  main:
    jobs:
      - build:
          context: SonarCloud
